sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    browser-->>server: {"note": "test2"}
    deactivate server

    Note right of browser: The browser executes the code that renders the new note.
